name: 'Create Release Tag'
description: 'Creates a new release tag based on semver input'
inputs:
  semver:
    description: 'Semver type (major.minor.patch)'
    required: true
    default: 'patch'
  sha:
    description: 'Commit SHA'
    required: false
  github-token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Next tag
      uses: neal2034/useful-git-actions/.github/actions/next-tag@main
      id: tag
      with:
        semver: ${{ inputs.semver }}
        sha: ${{ inputs.sha }}

    - name: Create tag
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/${{ steps.tag.outputs.tag }}',
            sha: '${{ steps.tag.outputs.sha }}',
          })